### ISSUE TITLE
Can you tell me what error is this  ?

### ISSUE THREAD

**Issue by rsoorajs** [eidoriantan/messenger-translator-telegram#7]
Heroku logs

`telegram
      
Application Logs
2021-01-20T08:02:33.887274+00:00 heroku[web.1]: Restarting
2021-01-20T08:02:33.889872+00:00 heroku[web.1]: State changed from up to starting
2021-01-20T08:02:35.315587+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2021-01-20T08:02:35.421650+00:00 heroku[web.1]: Process exited with status 143
2021-01-20T08:02:37.387765+00:00 heroku[web.1]: Starting process with command `node server.js`
2021-01-20T08:02:41.958823+00:00 app[web.1]: Connecting to SQL server...
2021-01-20T08:02:42.106153+00:00 app[web.1]: [bot.plugin] loaded 'regExpMessage' plugin
2021-01-20T08:02:42.107086+00:00 app[web.1]: [bot.plugin] loaded 'shortReply' plugin
2021-01-20T08:02:42.397416+00:00 app[web.1]: [bot.webhook] set to "https://messengertranslator.herokuapp.com/827475756:AAEUjtuYM4YnhfPYR2fXId2DU4B1PK9Phks"
2021-01-20T08:02:43.008111+00:00 heroku[web.1]: State changed from starting to up
2021-01-20T08:03:05.711531+00:00 heroku[router]: at=info method=POST path="/827475756:AAEUjtuYM4YnhfPYR2fXId2DU4B1PK9Phks" host=messengertranslator.herokuapp.com request_id=57f3bb8f-7062-4571-a223-67ad8c336888 fwd="91.108.6.130" dyno=web.1 connect=0ms service=9ms status=200 bytes=94 protocol=https
2021-01-20T08:03:05.710227+00:00 app[web.1]: [bot.error.event] TypeError: The "config.server" property is required and must be of type string.
2021-01-20T08:03:05.710238+00:00 app[web.1]:     at new Connection (/app/node_modules/tedious/lib/connection.js:121:13)
2021-01-20T08:03:05.710238+00:00 app[web.1]:     at /app/node_modules/mssql/lib/tedious/connection-pool.js:61:23
2021-01-20T08:03:05.710239+00:00 app[web.1]:     at new Promise (<anonymous>)
2021-01-20T08:03:05.710239+00:00 app[web.1]:     at ConnectionPool._poolCreate (/app/node_modules/mssql/lib/tedious/connection-pool.js:12:12)
2021-01-20T08:03:05.710240+00:00 app[web.1]:     at ConnectionPool._connect (/app/node_modules/mssql/lib/base/connection-pool.js:175:10)
2021-01-20T08:03:05.710241+00:00 app[web.1]:     at /app/node_modules/mssql/lib/base/connection-pool.js:147:19
2021-01-20T08:03:05.710241+00:00 app[web.1]:     at new Promise (<anonymous>)
2021-01-20T08:03:05.710242+00:00 app[web.1]:     at ConnectionPool.connect (/app/node_modules/mssql/lib/base/connection-pool.js:146:12)
2021-01-20T08:03:05.710242+00:00 app[web.1]:     at Object.connect (/app/node_modules/mssql/lib/global-connection.js:59:27)
2021-01-20T08:03:05.710243+00:00 app[web.1]:     at Object.getUser (/app/src/users.js:79:13)
2021-01-20T08:03:08.037193+00:00 heroku[router]: at=info method=POST path="/827475756:AAEUjtuYM4YnhfPYR2fXId2DU4B1PK9Phks" host=messengertranslator.herokuapp.com request_id=481140b3-ed77-4d3d-b08e-7d319cce2760 fwd="91.108.6.130" dyno=web.1 connect=0ms service=4ms status=200 bytes=94 protocol=https
2021-01-20T08:03:08.037091+00:00 app[web.1]: [bot.error.event] TypeError: The "config.server" property is required and must be of type string.
2021-01-20T08:03:08.037143+00:00 app[web.1]:     at new Connection (/app/node_modules/tedious/lib/connection.js:121:13)
2021-01-20T08:03:08.037144+00:00 app[web.1]:     at /app/node_modules/mssql/lib/tedious/connection-pool.js:61:23
2021-01-20T08:03:08.037145+00:00 app[web.1]:     at new Promise (<anonymous>)
2021-01-20T08:03:08.037145+00:00 app[web.1]:     at ConnectionPool._poolCreate (/app/node_modules/mssql/lib/tedious/connection-pool.js:12:12)
2021-01-20T08:03:08.037146+00:00 app[web.1]:     at ConnectionPool._connect (/app/node_modules/mssql/lib/base/connection-pool.js:175:10)
2021-01-20T08:03:08.037147+00:00 app[web.1]:     at /app/node_modules/mssql/lib/base/connection-pool.js:147:19
2021-01-20T08:03:08.037147+00:00 app[web.1]:     at new Promise (<anonymous>)
2021-01-20T08:03:08.037148+00:00 app[web.1]:     at ConnectionPool.connect (/app/node_modules/mssql/lib/base/connection-pool.js:146:12)
2021-01-20T08:03:08.037148+00:00 app[web.1]:     at Object.connect (/app/node_modules/mssql/lib/global-connection.js:59:27)
2021-01-20T08:03:08.037149+00:00 app[web.1]:     at Object.getUser (/app/src/users.js:79:13)`

**Comment by rsoorajs** [comment]
This is the error

`TypeError: The "config.server" property is required and must be of type string`

**Comment by telegrambotdev** [comment]
![IMG_20210120_133854_867](https://user-images.githubusercontent.com/20116017/105145533-e55d9d80-5b24-11eb-900d-55810c42fcdb.jpg)

**Comment by rsoorajs** [comment]
i filled out every env var..

i am running this app on heroku,and mysql db is running on my personal server.can you help me to solve this issue ?

**Comment by telegrambotdev** [comment]
![IMG_20210120_135054_206](https://user-images.githubusercontent.com/20116017/105147164-cbbd5580-5b26-11eb-9c00-f22529239f74.jpg)

**Comment by rsoorajs** [comment]
i put correct `SERVER`  env var along with port,like

5.765.64.45:3306

**Comment by eidoriantan** [comment]
The error could be because Microsoft's SQL Server is different than MySQL.

**Comment by eidoriantan** [comment]
They're not also compatible with each other so you have to install MSSQL instead of MySQL

**Comment by rsoorajs** [comment]
Thank you
